<?xml version="1.0" encoding="utf-8"?><Database Name="dbiLocator" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=dbiLocator;Integrated Security=True" SettingsObjectName="iLocatorAstar.Properties.Settings" SettingsPropertyName="dbiLocatorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUserLogs" Member="tblUserLogs">
    <Type Name="tblUserLog">
      <Column Name="userLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="currentLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="destination" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userLogTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_AddUserLogs" Method="sp_AddUserLogs">
    <Parameter Name="utype" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="start" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="dest" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="logTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ViewUserLogs" Method="sp_ViewUserLogs">
    <ElementType Name="sp_ViewUserLogsResult">
      <Column Name="userLogID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="currentLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="destination" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userLogTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>